"""Deterministic topology-based triplet closure proposals."""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

from .ontology import Ontology
from .topology import build_graph
from .triage import find_hubs
from .typed_edges import infer_note_type
from .walker import Note

_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]{2,}")
_BORING_TAGS = {
    "bookmark", "bookmarks", "firefox", "pocket", "web-content", "clipping",
    "clippings", "stub", "overview", "index", "hub", "map", "catalog", "directory",
    "github", "repository", "unknown", "html", "python", "typescript", "javascript",
}
_STOP_TOKENS = {
    "the", "and", "for", "with", "from", "that", "this", "into", "your", "their",
    "about", "over", "under", "what", "when", "where", "would", "could", "should",
    "welcome", "google", "docs", "sheet", "sheets", "guide", "homepage", "page",
    "https", "http", "www", "com", "html", "article", "code", "live",
}
_GENERIC_DOMAINS = {"docs.google.com", "drive.google.com"}
_GENERIC_WITNESS_TOKENS = {"overview", "index", "hub", "kanban", "map", "directory", "catalog"}


@dataclass
class TopologyProposal:
    source: str
    target: str
    predicate: str
    confidence: str
    rationale: str
    evidence: str
    score: int
    hub: str


def plan_topology_proposals(
    notes: list[Note],
    ontology: Ontology,
    *,
    per_hub_limit: int = 20,
    per_note_limit: int = 3,
) -> list[TopologyProposal]:
    graph, _ = build_graph(notes)
    note_by_path = {n.relpath: n for n in notes}
    hubs = find_hubs(notes, graph)
    hub_paths = {h.relpath for h in hubs}
    existing = {tuple(sorted((u, v))) for u, v in graph.edges()}

    proposals: list[TopologyProposal] = []
    proposals_per_note: dict[str, int] = {}

    for hub in hubs:
        hub_note = note_by_path.get(hub.relpath)
        if hub_note is None:
            continue
        neighbors = sorted(n for n in graph.neighbors(hub.relpath) if n != hub.relpath)
        ranked: list[TopologyProposal] = []
        for i, left in enumerate(neighbors):
            if left in hub_paths:
                continue
            for right in neighbors[i + 1:]:
                if right in hub_paths:
                    continue
                pair = tuple(sorted((left, right)))
                if pair in existing:
                    continue
                if proposals_per_note.get(left, 0) >= per_note_limit or proposals_per_note.get(right, 0) >= per_note_limit:
                    continue
                proposal = _score_pair(
                    note_by_path[left],
                    note_by_path[right],
                    hub_note,
                    graph,
                    ontology,
                    hub_paths,
                )
                if proposal is not None:
                    ranked.append(proposal)

        ranked.sort(key=lambda p: (-p.score, p.source, p.target))
        for proposal in ranked:
            if len([p for p in proposals if p.hub == proposal.hub]) >= per_hub_limit:
                break
            if proposals_per_note.get(proposal.source, 0) >= per_note_limit:
                continue
            if proposals_per_note.get(proposal.target, 0) >= per_note_limit:
                continue
            proposals.append(proposal)
            proposals_per_note[proposal.source] = proposals_per_note.get(proposal.source, 0) + 1
            proposals_per_note[proposal.target] = proposals_per_note.get(proposal.target, 0) + 1

    return proposals


def write_topology_proposals_md(proposals: list[TopologyProposal], out_path: Path) -> None:
    parts = [
        "# Proposals",
        "",
        "Generated by `edge-finder propose --plan --mode topology`.",
        "Only high-confidence topology closures are included.",
        "",
        "Check the box next to proposals you want applied. Then run:",
        "    edge-finder apply <vault>",
        "",
        "---",
        "",
    ]
    for i, proposal in enumerate(proposals, 1):
        parts.append(f"## {i}. `{proposal.source}` → `{proposal.target}`")
        parts.append("")
        parts.append(f"- [x] Apply: predicate=`{proposal.predicate}`, confidence={proposal.confidence}")
        parts.append(f"- Evidence: \"{proposal.evidence}\"")
        parts.append(f"- Rationale: {proposal.rationale}")
        parts.append("")
    if not proposals:
        parts.append("_No high-confidence topology closures were found._")
        parts.append("")
    out_path.write_text("\n".join(parts), encoding="utf-8")


def _score_pair(
    left: Note,
    right: Note,
    hub: Note,
    graph,
    ontology: Ontology,
    hub_paths: set[str],
) -> TopologyProposal | None:
    left_type = infer_note_type(left, ontology, hub_paths=hub_paths)
    right_type = infer_note_type(right, ontology, hub_paths=hub_paths)
    valid, _ = ontology.validate_triple(left_type, "co_topic", right_type)
    if not valid:
        return None

    hub_topic_tokens = _title_tokens(hub)
    shared_tags = sorted((_specific_tags(left) & _specific_tags(right)) - hub_topic_tokens)
    shared_domains = sorted(_domains(left) & _domains(right))
    title_overlap = sorted(_title_tokens(left) & _title_tokens(right))
    extra_witnesses = sorted(
        witness for witness in (set(graph.neighbors(left.relpath)) & set(graph.neighbors(right.relpath))) - {hub.relpath}
        if witness not in hub_paths and not _is_generic_witness(witness)
    )

    has_tag_cluster = len(shared_tags) >= 2
    has_title_alignment = len(title_overlap) >= 2
    has_extra_witness = bool(extra_witnesses)
    same_family = _same_family(left, right)
    if not same_family and (_is_generic_note(left) or _is_generic_note(right)):
        return None
    if not (same_family or has_extra_witness or has_tag_cluster or (shared_tags and has_title_alignment)):
        return None

    score = (4 * len(shared_tags)) + (4 * len(shared_domains)) + (2 * min(len(title_overlap), 3)) + (3 * len(extra_witnesses))
    evidence_parts = [f"shared hub={hub.title}"]
    if shared_tags:
        evidence_parts.append("shared tags=" + ", ".join(shared_tags[:3]))
    if shared_domains:
        evidence_parts.append("shared domain=" + ", ".join(shared_domains[:2]))
    if len(title_overlap) >= 2:
        evidence_parts.append("title overlap=" + ", ".join(title_overlap[:3]))
    if extra_witnesses:
        evidence_parts.append("extra witness=" + ", ".join(Path(w).stem for w in extra_witnesses[:2]))

    rationale = (
        f"Both notes connect to `{hub.relpath}` and share enough independent metadata "
        f"signals to justify a direct `co_topic` edge."
    )
    return TopologyProposal(
        source=left.relpath,
        target=right.relpath,
        predicate="co_topic",
        confidence="high",
        rationale=rationale,
        evidence="; ".join(evidence_parts),
        score=score,
        hub=hub.relpath,
    )


def _specific_tags(note: Note) -> set[str]:
    return {tag.lower() for tag in note.tags if tag.lower() not in _BORING_TAGS and len(tag) >= 4}


def _domains(note: Note) -> set[str]:
    domains: set[str] = set()
    for key in ("url", "source", "link", "href"):
        value = note.frontmatter.get(key)
        if isinstance(value, str):
            domain = _domain(value)
            if domain:
                domains.add(domain)
    return domains


def _domain(value: str) -> str | None:
    parsed = urlparse(value)
    host = parsed.netloc.lower().removeprefix("www.")
    if not host or host in _GENERIC_DOMAINS:
        return None
    return host


def _title_tokens(note: Note) -> set[str]:
    if note.title.lower().startswith(("http", "https")):
        return set()
    return {
        token.lower()
        for token in _TOKEN_RE.findall(note.title)
        if token.lower() not in _STOP_TOKENS
    }


def _is_generic_witness(relpath: str) -> bool:
    tokens = _label_tokens(Path(relpath).stem)
    return bool(tokens & _GENERIC_WITNESS_TOKENS)


def _is_generic_note(note: Note) -> bool:
    return bool(_label_tokens(note.title) & _GENERIC_WITNESS_TOKENS)


def _same_family(left: Note, right: Note) -> bool:
    left_stem = _normalized_stem(left)
    right_stem = _normalized_stem(right)
    if left_stem == right_stem:
        return True
    if left_stem and right_stem and (left_stem.startswith(right_stem) or right_stem.startswith(left_stem)):
        return True
    return False


def _normalized_stem(note: Note) -> str:
    stem = re.sub(r"[^a-z0-9]+", "-", note.title.lower()).strip("-")
    return stem


def _label_tokens(text: str) -> set[str]:
    return {part for part in re.split(r"[^a-z0-9]+", text.lower()) if part}
