"""Holistic propose mode: build structured index, prepare LLM judgment batch.

This is the default mode for Claude Code subscribers. It prepares the
edge-finding prompt that --judge will execute. No LLM call here — --plan
is preview-only.

Architecture:
  1. Build per-note Fingerprint (deterministic, mostly Granola-section parsing
     and dimension extraction, all already done elsewhere).
  2. Concatenate populated fingerprints into a structured index document.
  3. Write judgment-batch.md = ontology + index + instructions + verifiability
     contract. This is the EXACT prompt --judge will send.
  4. Estimate tokens; warn when approaching context limits.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path

import yaml

from .cache import Cache, fingerprint as content_hash, ontology_version
from .fingerprint import Fingerprint, fingerprint_completeness
from .topology import build_graph
from .walker import Note


@dataclass
class HolisticPlanResult:
    n_notes: int = 0
    n_with_signal: int = 0
    n_sparse: int = 0
    estimated_tokens: int = 0
    fits_in_sonnet: bool = False
    fits_in_opus: bool = False
    existing_edges: int = 0


def _fp_to_yaml_block(fp: Fingerprint, body_snippet: str) -> str:
    """Render a single note's fingerprint as a compact YAML block.

    Empty fields are dropped to keep the index dense — LLM doesn't need
    to read 'attendees: []' for every non-meeting note.
    """
    block: dict = {"path": fp.path, "type": fp.type, "status": fp.status}
    if fp.note_date:
        block["date"] = fp.note_date
    if fp.attendees:
        block["attendees"] = fp.attendees
    if fp.projects_mentioned:
        block["projects"] = fp.projects_mentioned
    if fp.follow_ups:
        block["follow_ups"] = fp.follow_ups
    if fp.action_items:
        block["action_items"] = [
            {"text": a.text, "assignee": a.assignee} if a.assignee else a.text
            for a in fp.action_items
        ]
    if fp.decisions:
        block["decisions"] = fp.decisions
    if fp.summary:
        block["summary"] = fp.summary
    if fp.topics:
        block["topics"] = fp.topics
    if fp.money:
        block["money"] = [{"amount": m.raw, "currency": m.currency} for m in fp.money[:5]]
    if fp.deadlines:
        block["deadlines"] = [
            {"date": d.date_iso, "raw": d.raw} for d in fp.deadlines if d.date_iso
        ][:5]
    if fp.stack:
        block["stack"] = [s.name for s in fp.stack]
    if body_snippet:
        block["body_snippet"] = body_snippet
    return yaml.safe_dump(block, sort_keys=False, default_flow_style=False).strip()


def plan_holistic(
    notes: list[Note],
    fingerprints: list[Fingerprint],
    ontology: dict,
    cache: Cache,
    *,
    snippet_chars: int = 240,
    min_fields_for_signal: int = 2,
) -> tuple[HolisticPlanResult, str]:
    """Build the holistic judgment batch. Returns (result, batch_text)."""
    note_by_path = {n.relpath: n for n in notes}
    fp_by_path = {fp.path: fp for fp in fingerprints}

    # Existing graph — give the LLM context on what's already linked
    g, _ = build_graph(notes)
    existing_edges = list(g.edges())

    blocks: list[str] = []
    n_with_signal = 0
    n_sparse = 0
    for fp in fingerprints:
        filled, _total = fingerprint_completeness(fp)
        if filled >= min_fields_for_signal:
            n_with_signal += 1
        else:
            n_sparse += 1
        note = note_by_path.get(fp.path)
        snippet = ""
        if note:
            body = note.body.strip().replace("\n", " ")
            snippet = body[:snippet_chars] + ("…" if len(body) > snippet_chars else "")
        blocks.append(_fp_to_yaml_block(fp, snippet))

    index_text = "\n---\n".join(blocks)

    ontology_yaml = yaml.safe_dump(ontology, sort_keys=False, default_flow_style=False)

    existing_edges_str = "\n".join(
        f"  - [{u!r}, {v!r}]" for u, v in existing_edges[:200]
    )
    if len(existing_edges) > 200:
        existing_edges_str += f"\n  - ... and {len(existing_edges) - 200} more"

    onto_v = ontology_version(ontology)

    prompt = f"""# Edge Proposal — Judgment Batch

Generated by `edge-finder propose --plan --mode holistic`.
This file is the **exact prompt** that `propose --judge` will send to Claude.
No LLM has been called yet.

Ontology version: `{onto_v}`
Notes in index: {len(fingerprints)}

---

## Your task (Claude, when --judge runs)

You are reading a structured index of an Obsidian vault. Your job is to
propose **new edges** between notes — wikilinks the user should add — that
are missing from the existing graph.

**Hard rules — non-negotiable:**

1. Every proposed edge MUST cite an `evidence_quote` that appears verbatim
   in either the source's `body_snippet` or the target's `body_snippet`,
   or in one of their structured fields (decisions, summary, action_items).
   We will substring-check every quote you produce against the original
   note bodies. Quotes that don't match are auto-rejected.

2. Every proposed edge MUST use an `edge_type` from the ontology's
   `edge_types` list below. If no type fits, use `related_to` or skip
   the edge.

3. Do not propose an edge that already exists in the `existing_edges` list.

4. Confidence levels: `high` for explicit shared entity / explicit
   reference / strong topical evidence; `medium` for inferred shared
   topic; `low` for "feels related" — and `low` is not allowed in
   the output.

5. Aim for **precision over recall**. It is much better to miss a real
   edge than to propose a junk one. The user has to read every proposal.

## Output format

Produce a YAML list of proposed edges. Nothing else.

```yaml
proposals:
  - source: "<note path>"
    target: "<note path>"
    edge_type: "<one of the ontology edge_types>"
    evidence_quote: "<verbatim substring from source or target>"
    confidence: high|medium
    rationale: "<one sentence>"
```

---

## Ontology

```yaml
{ontology_yaml}
```

## Existing edges (do not duplicate)

```yaml
existing_edges:
{existing_edges_str if existing_edges_str else '  []'}
```

---

## Structured index of the vault

Each block below is one note's fingerprint. Empty fields are omitted.
The `body_snippet` is the first {snippet_chars} characters of the note,
provided so you can ground edge proposals when structured fields are sparse.

```yaml
---
{index_text}
```
"""

    # Estimate tokens — rough: 1 token per 4 chars
    estimated_tokens = len(prompt) // 4

    result = HolisticPlanResult(
        n_notes=len(fingerprints),
        n_with_signal=n_with_signal,
        n_sparse=n_sparse,
        estimated_tokens=estimated_tokens,
        fits_in_sonnet=estimated_tokens < 180_000,
        fits_in_opus=estimated_tokens < 950_000,
        existing_edges=len(existing_edges),
    )

    # Cache the fingerprints for downstream reuse
    fp_dump = [{"path": fp.path, **{k: v for k, v in asdict(fp).items() if v}} for fp in fingerprints]
    fp_cache_path = cache.cache_dir / "fingerprints.yaml"
    fp_cache_path.write_text(yaml.safe_dump(fp_dump, sort_keys=False, default_flow_style=False))

    return result, prompt
